@startuml Fashion-FolderDB
hide circle
skinparam linetype ortho

entity "classes (クラス)" as classes {
    * <<PK>> id                        : bigint unsigned : ユーザーID
    --
    * class_name                       : varchar(255)    : クラス名
    * password                         : varchar(255)    : パスワード
    * shop_name                        : varcher(255)    : 店の名前
    * class_room                       : varchar(255)    : 教室名
    * comment                          : text            : クラスのコメント
    * image_path                       : varchar(255)    : 自分のアイコンのPath
    ' * html_code                        : longtext        : htmlのコード
    ' * css_code                         : longtext        : cssのコード
    ' * js_code                          : longtext        : jsのコード
    * created_at                       : timestamp       : 作成日時
    * updated_at                       : timestamp       : 更新日時
}

entity "uploaded_images (画像保存)" as uploaded_images {
    * <<PK>> id                        : bigint unsigned : 画像ID
    --
    * <<FK>> class_id                  : bigint unsigned : クラスID
    * filename                         : varchar(255)    : 画像の保存ファイル
    * paht                             : varchar(255)    : 保存先のpath
    * created_at                       : timestamp       : 作成日時
    * updated_at                       : timestamp       : 更新日時
}

entity "code_save (コードセーブデータ)" as code_save {
    * <<PK>> id                        : bigint unsigned : セーブデータID
    --
    * <<FK>> class_id                  : bigint unsigned : クラスID
    * save_number                      : integer         : セーブデータ番号
    * html_code                        : longtext        : htmlのコード
    * css_code                         : longtext        : cssのコード
    * js_code                          : longtext        : jsのコード
    * main_save_date                   : boolean         : mainのコードかの判定
    * created_at                       : timestamp       : 作成日時
    * updated_at                       : timestamp       : 更新日時
}

classes ||--o{ uploaded_images : "1対多"
classes ||--o{ code_save : "1対多"
