@startuml Fashion-FolderDB
hide circle
skinparam linetype ortho

entity "classes (クラス)" as classes {
    * <<PK>> id                        : bigint unsigned : クラスID
    --
    * class_name                       : varchar(255)    : クラス名
    * password                         : varchar(255)    : パスワード
    * shop_name                        : varchar(255)    : 店の名前
    * class_room                       : varchar(255)    : 教室名
    * comment                          : text            : クラスのコメント
    * authority_id                     : bigint unsigned : 権限ID (FK)
    * mail                             : vqrchar(255)    : メールアドレス
    * is_first_login                   : boolean         : 初回ログインフラグ
    * created_at                       : timestamp       : 作成日時
    * updated_at                       : timestamp       : 更新日時
}

entity "class_images (クラス画像)" as class_images {
    * <<PK>> id                        : bigint unsigned : 画像ID
    --
    * <<FK>> class_id                  : bigint unsigned : クラスID
    * image_path                       : varchar(255)    : 画像のパス
    * created_at                       : timestamp       : 作成日時
    * updated_at                       : timestamp       : 更新日時
}

entity "uploaded_images (画像保存)" as uploaded_images {
    * <<PK>> id                        : bigint unsigned : 画像ID
    --
    * <<FK>> class_id                  : bigint unsigned : クラスID
    * filename                         : varchar(255)    : 画像の保存ファイル
    * path                             : varchar(255)    : 保存先のパス
    * created_at                       : timestamp       : 作成日時
    * updated_at                       : timestamp       : 更新日時
}

entity "code_save (コードセーブデータ)" as code_save {
    * <<PK>> id                        : bigint unsigned : セーブデータID
    --
    * <<FK>> class_id                  : bigint unsigned : クラスID
    * save_number                      : integer         : セーブデータ番号
    * html_code                        : longtext        : HTMLのコード
    * css_code                         : longtext        : CSSのコード
    * js_code                          : longtext        : JSのコード
    * main_save_date                   : boolean         : メインのコードかの判定
    * created_at                       : timestamp       : 作成日時
    * updated_at                       : timestamp       : 更新日時
}

entity "authorities (権限)" as authorities {
    * <<PK>> id                        : bigint unsigned : 権限ID
    --
    * authority_name                   : varchar(255)    : 権限名
    * created_at                       : timestamp       : 作成日時
    * updated_at                       : timestamp       : 更新日時
}

classes ||--o{ class_images : "1対多"
classes ||--o{ uploaded_images : "1対多"
classes ||--o{ code_save : "1対多"
classes ||--o{ authorities : "多対1"
@enduml